#Encoding: UTF-8
require "rake/gempackagetask"
require "rake/testtask"
require "rake/rdoctask"

Rake::TestTask.new("test") do |t|
  t.pattern = "test/**/test_*.rb"
  t.warning = true
end

Rake::RDocTask.new do |rd|
  rd.title = "au3 RDocs"
  rd.main = "lib/README.rdoc"
  rd.rdoc_files.include("lib/README.rdoc", "lib/HISTORY.rdoc", "lib/**/*.rb")
end

spec = Gem::Specification.new do |gemspec|
  gemspec.name = "au3"
  gemspec.summary = "A binding to the AutoItX3 Windows automation tool."
  gemspec.description =<<EOF
  au3 is a gem that provides Ruby bindings to the AutoIt Windows automation tool by 
using it's DLL interface AutoItX. 
EOF
  gemspec.requirements = ["Microsoft Windows", "AutoItX3.dll from AutoIt3"]
  gemspec.version = "0.1.2.dev"
  gemspec.author = "Marvin Gülker"
  gemspec.email = "sutniuq@gmx.net"
  gemspec.homepage = "http://auto.rubyforge.org/"
  gemspec.platform = Gem::Platform::RUBY
  gemspec.required_ruby_version = ">=1.9"
  gemspec.files = [Dir["test/**"], "lib/HISTORY.rdoc", "lib/README.rdoc", "lib/au3.rb", Dir["lib/AutoItX3/*.rb"]].flatten
  gemspec.has_rdoc = true
  gemspec.rdoc_options << "--title" << "au3 RDocs" << "--main" << "lib/README.rdoc"
  gemspec.rubyforge_project = "Automations"
  gemspec.test_files = Dir.glob("test/**/test_*.rb")
  gemspec.add_dependency("win32-api", ">=1.4")
  gemspec.add_development_dependency("test-unit", ">=2.0")
end
Rake::GemPackageTask.new(spec).define