#Encoding: UTF-8
#This file is part of Xdo. 
#Copyright © 2009 Marvin Gülker
#  Initia in potestate nostra sunt, de eventu fortuna iudicat. 
require "rake/gempackagetask"
require "rake/testtask"
begin
  require "hanna/rdoctask"
rescue LoadError
  require "rake/rdoctask"
end

spec = Gem::Specification.new do |s|
  s.name = "xdo"
  s.summary = "Simulate keyboard and mouse input via a ruby interface to xdotool and other console programs."
  s.description =<<DESCRIPTION
XDo is a library to automate your mouse, fake keyboard input and 
manipulate windows in a Linux X server environment. It's wrapped 
around a lot of command line tools (see requirements) of which xdotool 
is the main one, the others are usually installed. It's designed to work 
only with Ruby 1.9. 
DESCRIPTION
  s.add_development_dependency("test-unit", ">= 2.0")
  s.requirements = ["The xdotool command-line tool.", "The xsel command-line tool.", "xwininfo (usually installed)", "eject (usually installed)", "xkill (usually installed)"]
  s.version = "0.0.4.dev"
  s.author = "Marvin Gülker"
  s.email = "sutniuq@gmx.net"
  s.platform = Gem::Platform::RUBY
  s.required_ruby_version = ">=1.9"
  s.files = ["bin/xinfo.rb", Dir["lib/**/*.rb"], Dir["test/*.rb"], Dir["samples/*.rb"], "README.rdoc", "HISTORY.rdoc", "DEPRECATE.rdoc"].flatten
  s.executables = ["xinfo.rb"]
  s.has_rdoc = true
  s.rdoc_options << "--title" << "XDo RDocs" <<  "--main" << "README.rdoc"
  s.test_files = Dir["test/test_*.rb"]
  s.rubyforge_project = "Automations"
end
Rake::GemPackageTask.new(spec).define

Rake::RDocTask.new do |rd|
  rd.rdoc_files.include("lib/**/*.rb", "**/*.rdoc")
  rd.title = "XDo RDocs"
  rd.main = "README.rdoc"
end

Rake::TestTask.new("test") do |t|
  t.pattern = "test/test_*.rb"
  t.warning = true
end

desc "Tests XDo and then builds the gem file."
task :full_gem => [:test, :gem]